//! The committed host-benchmark artifact generator. Runs two sweeps over the pure
//! `find_cross`: one where the tick count grows (orders held proportional) so runtime
//! grows ~linearly, and one where the order count grows at a FIXED tick count so
//! runtime stays ~flat. Together these are the "cost is O(ticks), not O(orders)"
//! claim, in numbers.
//!
//! Writes `docs/bench/clearing_scaling.csv` + `clearing_scaling.md` at the workspace
//! root. The inputs are deterministic; only the nanosecond timings vary by machine.

use std::fmt::Write as _;
use std::path::PathBuf;

use tempo_bench::{synthetic_book, time_find_cross};

const TICK_SIZES: [usize; 4] = [64, 256, 1024, 4096];
const ORDER_COUNTS: [usize; 4] = [256, 1024, 4096, 16384];
const ITERS: u32 = 2000;

fn main() -> std::io::Result<()> {
    let mut csv = String::from("sweep,param,ns_per_call\n");
    let mut md = String::new();

    md.push_str("# Clearing host-benchmark — O(ticks), not O(orders)\n\n");
    md.push_str("Generated by `cargo run -p tempo-bench` (deterministic inputs; timings\n");
    md.push_str("are machine-dependent — the *shape* is the claim).\n\n");

    md.push_str("## Sweep 1 — runtime vs tick count (orders = 4×ticks)\n\n");
    md.push_str("| ticks | ns/find_cross |\n|------:|--------------:|\n");
    for &ticks in &TICK_SIZES {
        let (d, s) = synthetic_book(ticks, ticks * 4, 0xABCD);
        let ns = time_find_cross(&d, &s, ITERS);
        let _ = writeln!(md, "| {ticks} | {ns} |");
        let _ = writeln!(csv, "ticks,{ticks},{ns}");
    }

    md.push_str("\n## Sweep 2 — runtime vs order count (ticks fixed = 256)\n\n");
    md.push_str("| orders | ns/find_cross |\n|-------:|--------------:|\n");
    for &orders in &ORDER_COUNTS {
        let (d, s) = synthetic_book(256, orders, 0x1234);
        let ns = time_find_cross(&d, &s, ITERS);
        let _ = writeln!(md, "| {orders} | {ns} |");
        let _ = writeln!(csv, "orders,{orders},{ns}");
    }

    md.push_str(
        "\nSweep 1 grows ~linearly in ticks; Sweep 2 stays ~flat as orders grow 64× — \
         the histogram method's defining property.\n",
    );

    let out_dir = workspace_root().join("docs/bench");
    std::fs::create_dir_all(&out_dir)?;
    std::fs::write(out_dir.join("clearing_scaling.csv"), &csv)?;
    std::fs::write(out_dir.join("clearing_scaling.md"), &md)?;
    print!("{md}");
    println!("\nwrote {}", out_dir.join("clearing_scaling.md").display());
    Ok(())
}

fn workspace_root() -> PathBuf {
    // CARGO_MANIFEST_DIR = <ws>/crates/bench
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root")
        .to_path_buf()
}
