//! High-level typed client for the Tempo program. Owns the ids, constants, PDA
//! derivations, account decoders, ergonomic instruction builders (including the
//! cross-margin `live_mask` assembly), and off-chain preflight checks — layered
//! over `tempo-math` (the shared on-chain arithmetic).
//!
//! The `generated` module is autogenerated by Codama from the IDL; do not edit
//! it by hand — run `just generate-clients` after any IDL change.

// Suppress clippy noise from the codama-generated module (redundant imports,
// allow(unused), etc.) without infecting the rest of the crate.
#[allow(unused_imports, clippy::all)]
pub mod generated;

pub mod accounts;
#[cfg(feature = "client")]
pub mod client;
pub mod consts;
pub mod error;
pub mod ids;
pub mod ix;
pub mod pda;
pub mod preflight;
#[cfg(feature = "client")]
pub mod retry;

// Single source of truth for the shared address type: downstream crates use
// `tempo_sdk::Pubkey` rather than declaring their own solana-pubkey/solana-sdk.
pub use solana_pubkey::Pubkey;

#[cfg(feature = "client")]
pub use client::TempoClient;
pub use error::SdkError;
pub use ids::{PYTH_RECEIVER_ID, SOL_USD_FEED_ID, TEMPO_PROGRAM_ID};
pub use pda::MarketPdas;
#[cfg(feature = "client")]
pub use retry::benign;
