use alloc::vec;
use alloc::vec::Vec;
use codama::CodamaAccount;
use pinocchio::{
    account::AccountView,
    cpi::{Seed, Signer},
    error::ProgramError,
    Address,
};

use crate::errors::TempoProgramError;
use crate::traits::{
    AccountDeserialize, AccountSerialize, AccountSize, Discriminator, PdaAccount, PdaSeeds,
    TempoAccountDiscriminators, Versioned,
};
use crate::{assert_no_padding, le_field};

/// Slots the `Collect` window stays open before a crank may start accumulating
/// (system-design §3, freeze model). `process_chunk` refuses to fold the first
/// chunk until `phase_deadline_slot` is reached, so orders submitted anywhere in
/// the window land in the same batch. Production tunes this per market; this uses a
/// protocol constant (off-chain cranks can extend it via their own pacing).
pub const COLLECT_WINDOW_SLOTS: u64 = 2;

/// Auction phase for a market's current round.
///
/// Drives the three-phase clearing protocol (clearing-protocol §3):
/// `Collect` accepts/cancels orders → `Accumulating` folds them into the
/// histogram → `Discovered` has a published `ClearingResult` → `Settling`
/// lets users pull their fills.
#[repr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AuctionPhase {
    Collect = 0,
    Accumulating = 1,
    Discovered = 2,
    Settling = 3,
}

impl AuctionPhase {
    #[inline(always)]
    pub fn from_u8(value: u8) -> Result<Self, ProgramError> {
        match value {
            0 => Ok(Self::Collect),
            1 => Ok(Self::Accumulating),
            2 => Ok(Self::Discovered),
            3 => Ok(Self::Settling),
            _ => Err(TempoProgramError::AuctionWrongPhase.into()),
        }
    }
}

/// Market account state (the per-market control block).
///
/// Carries the clearing control block plus the funding index and
/// per-market risk config (maintenance/penalty/fee bps, crank fee). The `oracle`
/// is consumed by `update_funding`/`liquidate`/`read_oracle`.
///
/// # PDA Seeds
/// `[b"market", market_seed.as_ref()]`
///
/// # Zero-copy layout (`#[repr(C)]`, **alignment 1**)
/// All multi-byte integers are stored as little-endian byte arrays so the
/// struct has alignment 1. Account data is pointer-cast at byte offset 2 (after
/// the disc+version prefix), which is not 8-byte aligned, so native `u64`
/// fields would be an unaligned read. Accessors are generated by `le_field!`.
///
/// 5 × [u8;8] (40) + 2 × [u8;4] (8) + 3 × Address (96) + 2 × u8 (2) = 146.
#[derive(Clone, Debug, PartialEq, CodamaAccount)]
#[codama(field("discriminator", number(u8), default_value = 1))]
#[codama(discriminator(field = "discriminator"))]
#[codama(seed(type = string(utf8), value = "market"))]
#[codama(seed(name = "marketSeed", type = public_key))]
#[repr(C)]
pub struct Market {
    pub current_auction_id_le: [u8; 8],
    pub phase_deadline_slot_le: [u8; 8],
    pub tick_size_le: [u8; 8],
    pub last_bid_fill_price_le: [u8; 8],
    pub last_ask_fill_price_le: [u8; 8],
    pub orders_per_auction_cap_le: [u8; 4],
    pub num_ticks_le: [u8; 4],
    pub authority: Address,
    pub market_seed: Address,
    pub oracle: Address,
    /// Current auction phase (`AuctionPhase`).
    pub phase: u8,
    /// PDA bump.
    pub bump: u8,
    // --- funding (appended; keeps earlier field offsets stable) ---
    /// Monotonic funding index (signed, `funding.rs` `FUNDING_SCALE` units).
    pub funding_index_le: [u8; 16],
    /// Unix timestamp of the last `update_funding` (for rate-limiting accrual).
    pub last_funding_ts_le: [u8; 8],
    // --- per-market risk config (appended; offsets above stay stable) ---
    /// Pyth feed id this market's `oracle` account must carry (`oracle.rs`).
    pub oracle_feed_id: [u8; 32],
    /// Maintenance margin requirement in bps (per-market risk param).
    pub maintenance_margin_bps_le: [u8; 2],
    /// Liquidation penalty in bps (per-market risk param).
    pub liquidation_penalty_bps_le: [u8; 2],
    /// Maker fee in bps, SIGNED (negative = maker rebate); applied when `is_maker`.
    pub maker_fee_bps_le: [u8; 2],
    /// Taker fee in bps, SIGNED (negative = taker rebate); applied to takers.
    pub taker_fee_bps_le: [u8; 2],
    /// Integrator revenue share, in bps of the positive fee paid (0..=10_000).
    pub integrator_share_bps_le: [u8; 2],
    /// Flat fee paid to the `finalize_clear` cranker from the fee pool.
    pub crank_fee_le: [u8; 8],
    // --- Vault binding (appended; offsets above stay stable) ---
    /// Collateral mint this market settles in; binds the per-mint vault
    /// `[b"vault", collateral_mint]` to the market so a foreign vault cannot be
    /// supplied. Zero (`[0u8; 32]`) means no declared money path.
    pub collateral_mint: Address,
    // --- Maker quotes (VERSION 4; per-maker parametric liquidity) ---
    /// Next id assigned to a new `MakerQuote` (the marginal-tick tie-break order).
    pub next_quote_id_le: [u8; 8],
    /// Number of active maker quotes on this market (completeness denominator).
    pub active_maker_quote_count_le: [u8; 8],
    /// Maker quotes folded into the histogram this round (reset each round).
    pub folded_maker_quote_count_le: [u8; 8],
    // --- risk hardening (VERSION 5; appended, offsets stable) ---
    /// Total open long base units across all positions (open-interest tracking).
    pub oi_long_le: [u8; 16],
    /// Total open short base units across all positions (open-interest tracking).
    pub oi_short_le: [u8; 16],
    /// Socialized-loss index charged to the long side (signed, `FUNDING_SCALE` units, ADL).
    pub social_loss_index_long_le: [u8; 16],
    /// Socialized-loss index charged to the short side (signed, `FUNDING_SCALE` units, ADL).
    pub social_loss_index_short_le: [u8; 16],
    /// Last accepted effective mark (1e8) used for risk; advances ≤ cap per slot.
    pub effective_price_1e8_le: [u8; 8],
    /// Slot the effective price was last advanced.
    pub effective_price_slot_le: [u8; 8],
    /// Slot of the most recent fresh oracle update (staleness tracking).
    pub last_good_oracle_slot_le: [u8; 8],
    /// Max per-slot effective-price move in bps (meltdown brake; risk param).
    pub max_price_move_bps_per_slot_le: [u8; 2],
    /// Slots past `last_good_oracle_slot` before the feed is treated hard-stale (risk param).
    pub soft_stale_slots_le: [u8; 8],
    // --- oracle-anchored tick window (VERSION 7; appended, offsets stable) ---
    /// Price represented by histogram tick 0 this round (known-issues §2.7). The
    /// window is `[floor, floor + (num_ticks-1)·tick_size]`; `price_to_tick` maps
    /// `price → (price − floor)/tick_size`. Re-snapped onto the oracle at every
    /// `start_auction` (and `initialize_market`), and **frozen for the whole round**
    /// — the histogram is indexed by tick, so the anchor must not move mid-round.
    /// A stale/missing oracle carries the previous floor forward (never blocks the
    /// roll). Genesis default is `tick_size` (one tick), which reproduces the old
    /// zero-anchored window exactly.
    pub window_floor_price_le: [u8; 8],
    // --- pre-trade risk config (VERSION 8; appended, offsets stable) ---
    /// Initial-margin requirement in bps — the buffer locked at open/increase,
    /// **above** `maintenance_margin_bps`, so a position never opens exactly on its
    /// liquidation line (missing-features §1.2). Its inverse is the market's implicit
    /// max leverage (e.g. 1000 bps ⇒ 10×). Validated `≥ maintenance_margin_bps` at
    /// init; `0` ⇔ no money path (paired with `maintenance_margin_bps == 0`).
    pub initial_margin_bps_le: [u8; 2],
    /// Maximum notional (`|size|·entry`) a single position may hold, enforced at
    /// `submit_order` against the order's worst-case resulting position
    /// (missing-features §1.2). `0` = disabled. A per-position risk bound that the
    /// leverage limit does not give (a whale at low leverage).
    pub max_position_notional_le: [u8; 16],
    // --- sharding (VERSION 10; appended, offsets stable) ---
    /// Number of `OrderSlab` shards for this market (set at init). Orders are routed
    /// across shards `[0, num_slab_shards)` so submit/settle run in parallel.
    pub num_slab_shards_le: [u8; 2],
    /// Shards not yet fully folded THIS round — the O(1) completeness aggregate
    /// `finalize_clear` gates on. Each shard decrements it once when its
    /// `resting_count` reaches 0 (confirmed by a per-shard scan). Reset to
    /// `num_slab_shards` at each roll.
    pub shards_pending_le: [u8; 2],
    /// Shards reset (drained + zeroed) for the next round — the roll aggregate
    /// `start_auction` gates on. Each `reset_shard` increments it once; reset to 0 at
    /// roll (see clearing-protocol §4, freeze model).
    pub shards_ready_le: [u8; 2],
}

assert_no_padding!(
    Market,
    8 * 5
        + 4 * 2
        + 32 * 3
        + 1
        + 1
        + 16
        + 8
        + 32
        + 2
        + 2
        + 2
        + 2
        + 2
        + 8
        + 32
        + 8 * 3
        + 16 * 2
        + 16 * 2
        + 8
        + 8
        + 8
        + 2
        + 8
        + 8
        + 2
        + 16
        + 2
        + 2
        + 2
);

impl Discriminator for Market {
    const DISCRIMINATOR: u8 = TempoAccountDiscriminators::MarketDiscriminator as u8;
}

impl Versioned for Market {
    // v10 (sharding): appended `num_slab_shards` + the `shards_pending` (completeness)
    // and `shards_ready` (roll) aggregates. A market now has `num_slab_shards` slabs;
    // the single-slab layout is gone, so a pre-v10 market must be re-provisioned (the
    // version bump fails it loudly). An append is prefix-compatible for readers, but the
    // account is sized by `DATA_LEN`, so a shorter pre-v10 account fails the size check.
    //
    // v9 (PERF-1): removed the redundant `accumulated_order_count` /
    // `active_order_count` mirror fields so `submit_order`/`cancel_order` no longer
    // write-lock `Market` (known-issues §2.1). The authoritative live-order count is
    // `OrderSlabHeader.count` and the authoritative folded count is
    // `AuctionHistogram.accumulated_count`; the completeness/censorship guarantee in
    // `finalize_clear` already rests on the `all_active_orders_accumulated` slab scan,
    // not on these counters. Removing fields from the prefix is NOT append-compatible,
    // so a pre-v9 account must be re-provisioned (the version bump fails it loudly).
    //
    // v8: appended `initial_margin_bps` (the initial-margin buffer above maintenance)
    // and `max_position_notional` (per-position notional cap) for pre-trade safety
    // (missing-features §1.1/§1.2). An append is layout-compatible for prefix readers,
    // but the account is sized by `DATA_LEN`, so a pre-v8 account is shorter and must
    // be re-provisioned; the version bump fails a stale account loudly.
    //
    // v7: appended `window_floor_price` for the oracle-anchored tick window
    // (known-issues §2.7). An append IS layout-compatible for readers of the
    // prefix, but the account is sized by `DATA_LEN`, so a pre-v7 account is
    // shorter and must be re-provisioned (dev-phase: re-provision is free). The
    // version bump makes a stale account fail the zero-copy check loudly.
    //
    // v6: the dead `sync_fee_multiplier` byte was removed from the prefix
    // (known-issues §3). A prefix change is NOT append-compatible, so that bump
    // made any pre-v6 account fail the zero-copy version check loudly instead of
    // decoding off-by-one — old accounts must be re-provisioned, not migrated.
    const VERSION: u8 = 10;
}

impl AccountSize for Market {
    const DATA_LEN: usize = 8 * 5
        + 4 * 2
        + 32 * 3
        + 1
        + 1
        + 16
        + 8
        + 32
        + 2
        + 2
        + 2
        + 2
        + 2
        + 8
        + 32
        + 8 * 3
        + 16 * 2
        + 16 * 2
        + 8
        + 8
        + 8
        + 2
        + 8
        + 8
        + 2
        + 16
        + 2
        + 2
        + 2;
}

impl AccountDeserialize for Market {}

impl AccountSerialize for Market {
    #[inline(always)]
    fn to_bytes_inner(&self) -> Vec<u8> {
        let mut data = Vec::with_capacity(Self::DATA_LEN);
        data.extend_from_slice(&self.current_auction_id_le);
        data.extend_from_slice(&self.phase_deadline_slot_le);
        data.extend_from_slice(&self.tick_size_le);
        data.extend_from_slice(&self.last_bid_fill_price_le);
        data.extend_from_slice(&self.last_ask_fill_price_le);
        data.extend_from_slice(&self.orders_per_auction_cap_le);
        data.extend_from_slice(&self.num_ticks_le);
        data.extend_from_slice(self.authority.as_ref());
        data.extend_from_slice(self.market_seed.as_ref());
        data.extend_from_slice(self.oracle.as_ref());
        data.push(self.phase);
        data.push(self.bump);
        data.extend_from_slice(&self.funding_index_le);
        data.extend_from_slice(&self.last_funding_ts_le);
        data.extend_from_slice(&self.oracle_feed_id);
        data.extend_from_slice(&self.maintenance_margin_bps_le);
        data.extend_from_slice(&self.liquidation_penalty_bps_le);
        data.extend_from_slice(&self.maker_fee_bps_le);
        data.extend_from_slice(&self.taker_fee_bps_le);
        data.extend_from_slice(&self.integrator_share_bps_le);
        data.extend_from_slice(&self.crank_fee_le);
        data.extend_from_slice(self.collateral_mint.as_ref());
        data.extend_from_slice(&self.next_quote_id_le);
        data.extend_from_slice(&self.active_maker_quote_count_le);
        data.extend_from_slice(&self.folded_maker_quote_count_le);
        data.extend_from_slice(&self.oi_long_le);
        data.extend_from_slice(&self.oi_short_le);
        data.extend_from_slice(&self.social_loss_index_long_le);
        data.extend_from_slice(&self.social_loss_index_short_le);
        data.extend_from_slice(&self.effective_price_1e8_le);
        data.extend_from_slice(&self.effective_price_slot_le);
        data.extend_from_slice(&self.last_good_oracle_slot_le);
        data.extend_from_slice(&self.max_price_move_bps_per_slot_le);
        data.extend_from_slice(&self.soft_stale_slots_le);
        data.extend_from_slice(&self.window_floor_price_le);
        data.extend_from_slice(&self.initial_margin_bps_le);
        data.extend_from_slice(&self.max_position_notional_le);
        data.extend_from_slice(&self.num_slab_shards_le);
        data.extend_from_slice(&self.shards_pending_le);
        data.extend_from_slice(&self.shards_ready_le);
        data
    }
}

impl PdaSeeds for Market {
    const PREFIX: &'static [u8] = b"market";

    #[inline(always)]
    fn seeds(&self) -> Vec<&[u8]> {
        vec![Self::PREFIX, self.market_seed.as_ref()]
    }

    #[inline(always)]
    fn seeds_with_bump<'a>(&'a self, bump: &'a [u8; 1]) -> Vec<Seed<'a>> {
        vec![
            Seed::from(Self::PREFIX),
            Seed::from(self.market_seed.as_ref()),
            Seed::from(bump.as_slice()),
        ]
    }
}

impl PdaAccount for Market {
    #[inline(always)]
    fn bump(&self) -> u8 {
        self.bump
    }
}

impl Market {
    le_field!(
        current_auction_id,
        set_current_auction_id,
        current_auction_id_le,
        u64
    );
    le_field!(
        phase_deadline_slot,
        set_phase_deadline_slot,
        phase_deadline_slot_le,
        u64
    );
    le_field!(tick_size, set_tick_size, tick_size_le, u64);
    le_field!(
        last_bid_fill_price,
        set_last_bid_fill_price,
        last_bid_fill_price_le,
        u64
    );
    le_field!(
        last_ask_fill_price,
        set_last_ask_fill_price,
        last_ask_fill_price_le,
        u64
    );
    le_field!(
        orders_per_auction_cap,
        set_orders_per_auction_cap,
        orders_per_auction_cap_le,
        u32
    );
    le_field!(num_ticks, set_num_ticks, num_ticks_le, u32);
    le_field!(funding_index, set_funding_index, funding_index_le, i128);
    le_field!(
        last_funding_ts,
        set_last_funding_ts,
        last_funding_ts_le,
        u64
    );

    #[inline(always)]
    pub fn maintenance_margin_bps(&self) -> u16 {
        u16::from_le_bytes(self.maintenance_margin_bps_le)
    }

    /// Initial-margin requirement in bps (the buffer locked at open/increase, above
    /// maintenance). Falls back to `maintenance_margin_bps` when zero so a pre-v8
    /// re-provisioned market (or a no-money-path market) keeps the old behaviour.
    #[inline(always)]
    pub fn initial_margin_bps(&self) -> u16 {
        let im = u16::from_le_bytes(self.initial_margin_bps_le);
        if im == 0 {
            self.maintenance_margin_bps()
        } else {
            im
        }
    }

    #[inline(always)]
    pub fn liquidation_penalty_bps(&self) -> u16 {
        u16::from_le_bytes(self.liquidation_penalty_bps_le)
    }

    le_field!(next_quote_id, set_next_quote_id, next_quote_id_le, u64);
    le_field!(
        active_maker_quote_count,
        set_active_maker_quote_count,
        active_maker_quote_count_le,
        u64
    );
    le_field!(
        folded_maker_quote_count,
        set_folded_maker_quote_count,
        folded_maker_quote_count_le,
        u64
    );
    le_field!(oi_long, set_oi_long, oi_long_le, u128);
    le_field!(oi_short, set_oi_short, oi_short_le, u128);
    le_field!(
        social_loss_index_long,
        set_social_loss_index_long,
        social_loss_index_long_le,
        i128
    );
    le_field!(
        social_loss_index_short,
        set_social_loss_index_short,
        social_loss_index_short_le,
        i128
    );
    le_field!(
        effective_price_1e8,
        set_effective_price_1e8,
        effective_price_1e8_le,
        u64
    );
    le_field!(
        effective_price_slot,
        set_effective_price_slot,
        effective_price_slot_le,
        u64
    );
    le_field!(
        last_good_oracle_slot,
        set_last_good_oracle_slot,
        last_good_oracle_slot_le,
        u64
    );
    le_field!(
        soft_stale_slots,
        set_soft_stale_slots,
        soft_stale_slots_le,
        u64
    );
    le_field!(
        window_floor_price,
        set_window_floor_price,
        window_floor_price_le,
        u64
    );
    le_field!(
        max_position_notional,
        set_max_position_notional,
        max_position_notional_le,
        u128
    );
    le_field!(
        num_slab_shards,
        set_num_slab_shards,
        num_slab_shards_le,
        u16
    );
    le_field!(shards_pending, set_shards_pending, shards_pending_le, u16);
    le_field!(shards_ready, set_shards_ready, shards_ready_le, u16);

    #[inline(always)]
    pub fn max_price_move_bps_per_slot(&self) -> u16 {
        u16::from_le_bytes(self.max_price_move_bps_per_slot_le)
    }

    /// Apply a signed open-interest delta from a position size change
    /// (`old_signed` → `new_signed`, base units). Saturating; keeps `oi_long` and
    /// `oi_short` as the running totals of long and short exposure.
    pub fn apply_oi_delta(&mut self, old_signed: i128, new_signed: i128) {
        let old_long = old_signed.max(0) as u128;
        let new_long = new_signed.max(0) as u128;
        let old_short = (-old_signed).max(0) as u128;
        let new_short = (-new_signed).max(0) as u128;
        self.set_oi_long(
            self.oi_long()
                .saturating_add(new_long)
                .saturating_sub(old_long),
        );
        self.set_oi_short(
            self.oi_short()
                .saturating_add(new_short)
                .saturating_sub(old_short),
        );
    }

    /// Socialize an uncovered bad-debt `residual` to the winning (counterparty)
    /// side by its open interest (ADL): a liquidated long's residual is
    /// charged to shorts, and vice-versa, via `+= residual·FUNDING_SCALE/winner_oi`.
    /// Returns `false` (without mutating) when there is no winning OI to absorb it,
    /// so the caller can log the unbacked remainder.
    pub fn socialize_bad_debt(
        &mut self,
        loser_signed_size: i128,
        residual: u64,
    ) -> Result<bool, ProgramError> {
        if residual == 0 {
            return Ok(true);
        }
        // A liquidated long (size > 0) is funded by the shorts → charge shorts.
        let winner_is_long = loser_signed_size < 0;
        let winner_oi = if winner_is_long {
            self.oi_long()
        } else {
            self.oi_short()
        };
        if winner_oi == 0 {
            return Ok(false);
        }
        // Round the per-unit index increment UP (against winners): the per-position
        // charge in `Position::settle_social_loss` floors again, so a floored index
        // here double-floors and makes `Σ charges < residual` — leaving dust the last
        // winner's settle can't cover, reverting it `InsuranceInsolvent`. Ceiling the
        // index increment makes `winner_oi · add / FUNDING_SCALE ≥ residual`, so the
        // socialized charges cover the residual instead of falling short (HS-8).
        let add = crate::wide_math::mul_div_ceil(
            residual as u128,
            crate::funding::FUNDING_SCALE as u128,
            winner_oi,
        )
        .ok_or(TempoProgramError::MathOverflow)?;
        let add = i128::try_from(add).map_err(|_| TempoProgramError::MathOverflow)?;
        if winner_is_long {
            self.set_social_loss_index_long(self.social_loss_index_long().saturating_add(add));
        } else {
            self.set_social_loss_index_short(self.social_loss_index_short().saturating_add(add));
        }
        Ok(true)
    }

    /// Walk the stored effective risk price toward a fresh `oracle_1e8` by at most
    /// the per-slot cap (brake), persist it + the freshness stamp, and return
    /// the new mark.
    pub fn advance_effective_price(&mut self, oracle_1e8: u64, now_slot: u64) -> u64 {
        let new_eff = crate::mark::clamp_price_step(
            self.effective_price_1e8(),
            oracle_1e8,
            self.max_price_move_bps_per_slot(),
            now_slot.saturating_sub(self.effective_price_slot()),
        );
        self.set_effective_price_1e8(new_eff);
        self.set_effective_price_slot(now_slot);
        self.set_last_good_oracle_slot(now_slot);
        new_eff
    }

    /// Re-snap the tick window onto a fresh `oracle_1e8`, centering it so the
    /// oracle sits in the middle of the `num_ticks` band (known-issues §2.7):
    /// `floor = oracle − (num_ticks/2)·tick_size`, snapped down to a tick multiple
    /// and clamped to at least one tick (price 0 is invalid). Called only when a
    /// round opens (`start_auction`/`initialize_market`), never mid-round, so the
    /// histogram's tick→price meaning is constant for the whole round. A zero
    /// `oracle_1e8` (no usable price) is a no-op — the caller carries the previous
    /// floor forward.
    pub fn recenter_window(&mut self, oracle_1e8: u64) {
        let tick_size = self.tick_size();
        if oracle_1e8 == 0 || tick_size == 0 {
            return;
        }
        let half = (self.num_ticks() as u64 / 2).saturating_mul(tick_size);
        let raw_floor = oracle_1e8.saturating_sub(half);
        // Snap down to a tick multiple so every in-window price stays a clean
        // multiple of `tick_size` (keeps `validate_price` and `price_to_tick`
        // consistent), and never below one tick.
        let snapped = (raw_floor / tick_size).saturating_mul(tick_size);
        self.set_window_floor_price(snapped.max(tick_size));
    }

    // NOTE: the former `risk_price` (the braked effective mark as a solvency price)
    // was removed with known-issues §2.2 — solvency is now priced off the RAW
    // per-leg oracle via `oracle::solvency_mark` in `liquidate`, `liquidate_cross`,
    // and `withdraw_cross`, so the per-slot brake can no longer delay a liquidation
    // or permit over-withdrawal during a crash. `effective_price_1e8` remains the
    // braked mark for funding + the soft-stale fallback.

    #[inline(always)]
    pub fn maker_fee_bps(&self) -> i16 {
        i16::from_le_bytes(self.maker_fee_bps_le)
    }

    #[inline(always)]
    pub fn taker_fee_bps(&self) -> i16 {
        i16::from_le_bytes(self.taker_fee_bps_le)
    }

    #[inline(always)]
    pub fn integrator_share_bps(&self) -> u16 {
        u16::from_le_bytes(self.integrator_share_bps_le)
    }

    #[inline(always)]
    pub fn crank_fee(&self) -> u64 {
        u64::from_le_bytes(self.crank_fee_le)
    }

    /// Construct a fresh market in `Collect` phase, auction id 0.
    #[allow(clippy::too_many_arguments)]
    #[inline(always)]
    pub fn new(
        bump: u8,
        authority: Address,
        market_seed: Address,
        oracle: Address,
        oracle_feed_id: [u8; 32],
        tick_size: u64,
        num_ticks: u32,
        orders_per_auction_cap: u32,
        maintenance_margin_bps: u16,
        liquidation_penalty_bps: u16,
        maker_fee_bps: i16,
        taker_fee_bps: i16,
        integrator_share_bps: u16,
        crank_fee: u64,
        collateral_mint: Address,
        max_price_move_bps_per_slot: u16,
        soft_stale_slots: u64,
        initial_margin_bps: u16,
        max_position_notional: u128,
        num_slab_shards: u16,
    ) -> Self {
        Self {
            current_auction_id_le: 0u64.to_le_bytes(),
            phase_deadline_slot_le: 0u64.to_le_bytes(),
            tick_size_le: tick_size.to_le_bytes(),
            last_bid_fill_price_le: 0u64.to_le_bytes(),
            last_ask_fill_price_le: 0u64.to_le_bytes(),
            orders_per_auction_cap_le: orders_per_auction_cap.to_le_bytes(),
            num_ticks_le: num_ticks.to_le_bytes(),
            authority,
            market_seed,
            oracle,
            phase: AuctionPhase::Collect as u8,
            bump,
            funding_index_le: 0i128.to_le_bytes(),
            last_funding_ts_le: 0u64.to_le_bytes(),
            oracle_feed_id,
            maintenance_margin_bps_le: maintenance_margin_bps.to_le_bytes(),
            liquidation_penalty_bps_le: liquidation_penalty_bps.to_le_bytes(),
            maker_fee_bps_le: maker_fee_bps.to_le_bytes(),
            taker_fee_bps_le: taker_fee_bps.to_le_bytes(),
            integrator_share_bps_le: integrator_share_bps.to_le_bytes(),
            crank_fee_le: crank_fee.to_le_bytes(),
            collateral_mint,
            next_quote_id_le: 0u64.to_le_bytes(),
            active_maker_quote_count_le: 0u64.to_le_bytes(),
            folded_maker_quote_count_le: 0u64.to_le_bytes(),
            oi_long_le: 0u128.to_le_bytes(),
            oi_short_le: 0u128.to_le_bytes(),
            social_loss_index_long_le: 0i128.to_le_bytes(),
            social_loss_index_short_le: 0i128.to_le_bytes(),
            effective_price_1e8_le: 0u64.to_le_bytes(),
            effective_price_slot_le: 0u64.to_le_bytes(),
            last_good_oracle_slot_le: 0u64.to_le_bytes(),
            max_price_move_bps_per_slot_le: max_price_move_bps_per_slot.to_le_bytes(),
            soft_stale_slots_le: soft_stale_slots.to_le_bytes(),
            // Genesis default: floor = one tick, reproducing the old zero-anchored
            // window exactly. `initialize_market`/`start_auction` recenter it on the
            // oracle when one is available.
            window_floor_price_le: tick_size.to_le_bytes(),
            initial_margin_bps_le: initial_margin_bps.to_le_bytes(),
            max_position_notional_le: max_position_notional.to_le_bytes(),
            num_slab_shards_le: num_slab_shards.to_le_bytes(),
            // Round 0 opens in Collect expecting every shard to be folded, so start the
            // completeness aggregate at the full shard count. `finalize_clear` is blocked
            // until each shard (created by `init_shard`) has been folded once, which drives
            // this to 0. No shards are reset yet.
            shards_pending_le: num_slab_shards.to_le_bytes(),
            shards_ready_le: 0u16.to_le_bytes(),
        }
    }

    #[inline(always)]
    pub fn from_account<'a>(
        data: &'a [u8],
        account: &AccountView,
        program_id: &Address,
    ) -> Result<&'a Self, ProgramError> {
        let state = Self::from_bytes(data)?;
        state.validate_self(account, program_id)?;
        Ok(state)
    }

    #[inline(always)]
    pub fn phase(&self) -> Result<AuctionPhase, ProgramError> {
        AuctionPhase::from_u8(self.phase)
    }

    #[inline(always)]
    pub fn require_phase(&self, expected: AuctionPhase) -> Result<(), ProgramError> {
        if self.phase()? != expected {
            return Err(TempoProgramError::AuctionWrongPhase.into());
        }
        Ok(())
    }

    #[inline(always)]
    pub fn validate_authority(&self, provided: &Address) -> Result<(), ProgramError> {
        if self.authority != *provided {
            return Err(TempoProgramError::InvalidAuthority.into());
        }
        Ok(())
    }

    /// Validate that `price` is non-zero and aligned to the market tick size.
    #[inline(always)]
    pub fn validate_price(&self, price: u64) -> Result<(), ProgramError> {
        let tick_size = self.tick_size();
        if price == 0 || tick_size == 0 || !price.is_multiple_of(tick_size) {
            return Err(TempoProgramError::InvalidPrice.into());
        }
        Ok(())
    }

    /// Map a price to its histogram tick index.
    ///
    /// Tick mapping (clearing-protocol §2): the window floor is `window_floor_price`
    /// (the price at tick 0, re-snapped onto the oracle each round — known-issues
    /// §2.7), so `tick = (price − floor)/tick_size`. The price must be tick-aligned
    /// and fall inside `[floor, floor + (num_ticks-1)·tick_size]`. When the floor is
    /// the genesis default (`tick_size`) this reduces to the old `price/tick_size −
    /// 1` mapping.
    #[inline(always)]
    pub fn price_to_tick(&self, price: u64) -> Result<u32, ProgramError> {
        price_to_tick_raw(
            price,
            self.window_floor_price(),
            self.tick_size(),
            self.num_ticks(),
        )
    }

    /// Inverse of `price_to_tick`: the price represented by a tick index.
    #[inline(always)]
    pub fn tick_to_price(&self, tick: u32) -> Result<u64, ProgramError> {
        if tick >= self.num_ticks() {
            return Err(TempoProgramError::InvalidTick.into());
        }
        (tick as u64)
            .checked_mul(self.tick_size())
            .and_then(|off| off.checked_add(self.window_floor_price()))
            .ok_or_else(|| TempoProgramError::MathOverflow.into())
    }

    /// Execute a CPI with this market PDA as signer.
    #[inline(always)]
    pub fn with_signer<F, R>(&self, f: F) -> R
    where
        F: FnOnce(&[Signer<'_, '_>]) -> R,
    {
        let bump_seed = [self.bump];
        let seeds = [
            Seed::from(Self::PREFIX),
            Seed::from(self.market_seed.as_ref()),
            Seed::from(bump_seed.as_slice()),
        ];
        let signers = [Signer::from(&seeds)];
        f(&signers)
    }
}

/// Borrow-free price→tick map shared by `Market::price_to_tick`, `process_chunk`,
/// and `settle_fill` so the three never drift (clearing-protocol §2). The window
/// floor is the price at tick 0 (oracle-anchored — known-issues §2.7), so
/// `tick = (price − floor)/tick_size`. The price must be non-zero, tick-aligned,
/// at or above the floor, and inside `[floor, floor + (num_ticks-1)·tick_size]`.
/// With `floor == tick_size` (genesis default) this is the old `price/tick_size −
/// 1` mapping.
#[inline(always)]
pub fn price_to_tick_raw(
    price: u64,
    floor: u64,
    tick_size: u64,
    num_ticks: u32,
) -> Result<u32, ProgramError> {
    // Price must be a clean tick multiple AND at/above the window floor. Tying the
    // alignment to the raw price (not the offset) keeps `validate_price` — which
    // checks `price % tick_size == 0` with no floor — consistent, because the
    // floor is itself snapped to a tick multiple in `recenter_window`.
    if price == 0 || tick_size == 0 || !price.is_multiple_of(tick_size) || price < floor {
        return Err(TempoProgramError::InvalidPrice.into());
    }
    let offset = (price - floor) / tick_size;
    if offset >= num_ticks as u64 {
        return Err(TempoProgramError::InvalidTick.into());
    }
    Ok(offset as u32)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::traits::Discriminator;

    fn test_market() -> Market {
        let authority = Address::new_from_array([2u8; 32]);
        let market_seed = Address::new_from_array([1u8; 32]);
        let oracle = Address::new_from_array([3u8; 32]);
        let collateral_mint = Address::new_from_array([4u8; 32]);
        Market::new(
            255,
            authority,
            market_seed,
            oracle,
            [7u8; 32],
            10,
            64,
            256,
            500,
            100,
            -5,
            20,
            5000,
            7,
            collateral_mint,
            50,
            30,
            600,
            0,
            16, // num_slab_shards
        )
    }

    #[test]
    fn test_market_new_defaults() {
        let m = test_market();
        assert_eq!(m.current_auction_id(), 0);
        assert_eq!(m.phase, AuctionPhase::Collect as u8);
        assert_eq!(m.tick_size(), 10);
        assert_eq!(m.num_slab_shards(), 16);
        assert_eq!(m.shards_pending(), 16);
        assert_eq!(m.shards_ready(), 0);
        assert_eq!(m.num_ticks(), 64);
        assert_eq!(m.orders_per_auction_cap(), 256);
    }

    #[test]
    fn test_market_roundtrip() {
        let m = test_market();
        let bytes = m.to_bytes();
        assert_eq!(bytes.len(), Market::LEN);
        assert_eq!(bytes[0], Market::DISCRIMINATOR);
        assert_eq!(bytes[1], Market::VERSION);

        let de = Market::from_bytes(&bytes).unwrap();
        assert_eq!(de.tick_size(), m.tick_size());
        assert_eq!(de.authority, m.authority);
        assert_eq!(de.market_seed, m.market_seed);
        assert_eq!(de.oracle, m.oracle);
        assert_eq!(de.bump, m.bump);
        assert_eq!(de.num_ticks(), m.num_ticks());
        assert_eq!(de.oracle_feed_id, m.oracle_feed_id);
        assert_eq!(de.maintenance_margin_bps(), 500);
        assert_eq!(de.liquidation_penalty_bps(), 100);
        assert_eq!(de.maker_fee_bps(), -5);
        assert_eq!(de.taker_fee_bps(), 20);
        assert_eq!(de.integrator_share_bps(), 5000);
        assert_eq!(de.crank_fee(), 7);
        assert_eq!(de.collateral_mint, m.collateral_mint);
    }

    #[test]
    fn test_market_setters_via_from_bytes_mut() {
        let m = test_market();
        let mut bytes = m.to_bytes();
        {
            let mm = Market::from_bytes_mut(&mut bytes).unwrap();
            mm.set_current_auction_id(5);
            mm.phase = AuctionPhase::Accumulating as u8;
        }
        let de = Market::from_bytes(&bytes).unwrap();
        assert_eq!(de.current_auction_id(), 5);
        assert_eq!(de.phase, AuctionPhase::Accumulating as u8);
    }

    #[test]
    fn test_market_seeds() {
        let m = test_market();
        let seeds = m.seeds();
        assert_eq!(seeds.len(), 2);
        assert_eq!(seeds[0], Market::PREFIX);
        assert_eq!(seeds[1], m.market_seed.as_ref());
    }

    #[test]
    fn test_validate_authority() {
        let m = test_market();
        assert!(m
            .validate_authority(&Address::new_from_array([2u8; 32]))
            .is_ok());
        assert_eq!(
            m.validate_authority(&Address::new_from_array([9u8; 32])),
            Err(TempoProgramError::InvalidAuthority.into())
        );
    }

    #[test]
    fn test_require_phase() {
        let m = test_market();
        assert!(m.require_phase(AuctionPhase::Collect).is_ok());
        assert_eq!(
            m.require_phase(AuctionPhase::Settling),
            Err(TempoProgramError::AuctionWrongPhase.into())
        );
    }

    #[test]
    fn test_validate_price() {
        let m = test_market(); // tick_size = 10
        assert!(m.validate_price(10).is_ok());
        assert!(m.validate_price(120).is_ok());
        assert_eq!(
            m.validate_price(0),
            Err(TempoProgramError::InvalidPrice.into())
        );
        assert_eq!(
            m.validate_price(15),
            Err(TempoProgramError::InvalidPrice.into())
        );
    }

    #[test]
    fn test_price_to_tick_roundtrip() {
        let m = test_market(); // tick_size = 10, num_ticks = 64
        assert_eq!(m.price_to_tick(10).unwrap(), 0);
        assert_eq!(m.price_to_tick(20).unwrap(), 1);
        assert_eq!(m.price_to_tick(640).unwrap(), 63);
        assert_eq!(m.tick_to_price(0).unwrap(), 10);
        assert_eq!(m.tick_to_price(63).unwrap(), 640);
        assert_eq!(
            m.price_to_tick(650),
            Err(TempoProgramError::InvalidTick.into())
        );
        assert_eq!(
            m.tick_to_price(64),
            Err(TempoProgramError::InvalidTick.into())
        );
    }

    #[test]
    fn test_price_to_tick_raw_agrees_with_method() {
        let m = test_market(); // tick_size = 10, num_ticks = 64, floor = 10 (genesis)
        let floor = m.window_floor_price();
        for mult in 1..=64u64 {
            let price = mult * 10;
            assert_eq!(
                price_to_tick_raw(price, floor, m.tick_size(), m.num_ticks()).unwrap(),
                m.price_to_tick(price).unwrap()
            );
        }
        assert_eq!(
            price_to_tick_raw(15, floor, m.tick_size(), m.num_ticks()),
            Err(TempoProgramError::InvalidPrice.into())
        );
        assert_eq!(
            price_to_tick_raw(650, floor, m.tick_size(), m.num_ticks()),
            Err(TempoProgramError::InvalidTick.into())
        );
    }

    #[test]
    fn test_genesis_window_floor_is_tick_size() {
        // `new()` defaults the floor to one tick, reproducing the old zero-anchored
        // window exactly (tick 0 == price tick_size).
        let m = test_market();
        assert_eq!(m.window_floor_price(), m.tick_size());
    }

    #[test]
    fn test_recenter_window_centers_on_oracle() {
        let mut bytes = test_market().to_bytes(); // tick_size 10, num_ticks 64
        let m = Market::from_bytes_mut(&mut bytes).unwrap();
        // Oracle at 10_000: floor = 10_000 - (64/2)*10 = 10_000 - 320 = 9_680,
        // already a tick multiple. The window then spans [9_680, 9_680 + 63*10].
        m.recenter_window(10_000);
        assert_eq!(m.window_floor_price(), 9_680);
        assert_eq!(m.tick_to_price(0).unwrap(), 9_680);
        assert_eq!(m.price_to_tick(10_000).unwrap(), 32);
        assert_eq!(m.tick_to_price(63).unwrap(), 9_680 + 630);
        // A price below the floor or above the top is now out of the window.
        assert_eq!(
            m.price_to_tick(9_670),
            Err(TempoProgramError::InvalidPrice.into())
        );
        assert_eq!(
            m.price_to_tick(9_680 + 640),
            Err(TempoProgramError::InvalidTick.into())
        );
    }

    #[test]
    fn test_recenter_window_snaps_to_tick_and_floors_at_one_tick() {
        let mut bytes = test_market().to_bytes();
        let m = Market::from_bytes_mut(&mut bytes).unwrap();
        // Oracle not on a tick boundary: floor snaps DOWN to a tick multiple.
        m.recenter_window(10_005); // 10_005 - 320 = 9_685 → snaps to 9_680
        assert_eq!(m.window_floor_price(), 9_680);
        // A tiny oracle can't push the floor below one tick (price 0 is invalid).
        m.recenter_window(5);
        assert_eq!(m.window_floor_price(), m.tick_size());
        // A zero oracle is a no-op (carry forward).
        let before = m.window_floor_price();
        m.recenter_window(0);
        assert_eq!(m.window_floor_price(), before);
    }

    #[test]
    fn test_clearing_price_map_uses_window_floor_cr1() {
        // CR-1 regression: `finalize_clear` maps a clearing tick to a price with the
        // canonical inverse `tick·tick_size + window_floor` (== `tick_to_price`), NOT
        // the legacy zero-anchored `(tick+1)·tick_size`, which ignored the
        // oracle-centered window floor and fabricated the clearing price on every
        // recentered market.
        let mut bytes = test_market().to_bytes(); // tick_size 10, num_ticks 64
        let m = Market::from_bytes_mut(&mut bytes).unwrap();
        m.recenter_window(10_000); // floor = 9_680
        let tick_size = m.tick_size();
        let window_floor = m.window_floor_price();
        for clearing_tick in [0u32, 1, 32, 63] {
            // The exact map `finalize_clear`'s `cross_price` closure now computes.
            let published = (clearing_tick as u64) * tick_size + window_floor;
            assert_eq!(published, m.tick_to_price(clearing_tick).unwrap());
            // The legacy (buggy) formula is wrong by exactly (window_floor - tick_size).
            let legacy = (clearing_tick as u64 + 1) * tick_size;
            assert_ne!(published, legacy);
            assert_eq!(published - legacy, window_floor - tick_size);
        }
    }

    #[test]
    fn test_socialize_bad_debt_conserves_residual_hs8() {
        // HS-8 regression: the social-loss index increment is rounded UP (ceil) so the
        // socialized charge covers the residual instead of double-flooring below it.
        // With a single winner holding all the OI, the charge it later pays back is
        // `floor(winner_oi · add / FUNDING_SCALE)`, which must be ≥ residual. A floored
        // index increment (the old bug) would leave dust uncharged → `Σ < residual`.
        let scale = crate::funding::FUNDING_SCALE as u128;
        // winner_oi deliberately does NOT divide residual·scale, so a floored index
        // increment would lose dust and undercharge.
        let winner_oi: i128 = 3;
        let residual: u64 = 7;

        let mut bytes = test_market().to_bytes();
        let m = Market::from_bytes_mut(&mut bytes).unwrap();
        // Loser is short (size < 0) → winners are the longs; give the longs the OI.
        m.apply_oi_delta(0, winner_oi);
        assert!(m.socialize_bad_debt(-1, residual).unwrap());

        let add = m.social_loss_index_long(); // per-unit index increment (now ceil)
                                              // The single winner (all the OI) pays floor(|size| · add / scale).
        let charge = (winner_oi as u128) * (add as u128) / scale;
        assert!(
            charge >= residual as u128,
            "socialized charge {} < residual {}",
            charge,
            residual
        );
    }

    #[test]
    fn test_apply_oi_delta() {
        let mut bytes = test_market().to_bytes();
        let m = Market::from_bytes_mut(&mut bytes).unwrap();
        m.apply_oi_delta(0, 100); // open long 100
        assert_eq!(m.oi_long(), 100);
        assert_eq!(m.oi_short(), 0);
        m.apply_oi_delta(100, 60); // reduce long to 60
        assert_eq!(m.oi_long(), 60);
        m.apply_oi_delta(60, -40); // flip to short 40
        assert_eq!(m.oi_long(), 0);
        assert_eq!(m.oi_short(), 40);
        m.apply_oi_delta(-40, 0); // close
        assert_eq!(m.oi_long(), 0);
        assert_eq!(m.oi_short(), 0);
    }

    #[test]
    fn test_phase_from_u8() {
        assert_eq!(AuctionPhase::from_u8(0).unwrap(), AuctionPhase::Collect);
        assert_eq!(AuctionPhase::from_u8(3).unwrap(), AuctionPhase::Settling);
        assert!(AuctionPhase::from_u8(4).is_err());
    }
}
