// Single import surface over the generated Codama client. The runtime artifact
// is the esbuild bundle in `src/vendor/tempo-client.mjs` (regenerated by
// `pnpm bundle-client`, which runs on predev/prebuild); types come from the
// generated sources via the sibling `.d.mts`.
export * from "@/vendor/tempo-client.mjs";

import {
    getProgramDerivedAddress,
    getUtf8Encoder,
    type Address,
    type ProgramDerivedAddress,
} from "@solana/kit";
import {
    findEventAuthorityPda,
    findOrderSlabHeaderPda,
    findUserCollateralPda,
    findVaultPda,
    TEMPO_PROGRAM_PROGRAM_ADDRESS,
} from "@/vendor/tempo-client.mjs";

export const TEMPO_PROGRAM: Address = TEMPO_PROGRAM_PROGRAM_ADDRESS;

/** Auction phases (mirrors `state::market::AuctionPhase`). */
export const Phase = {
    Collect: 0,
    Accumulating: 1,
    Discovered: 2,
    Settling: 3,
} as const;

export type PhaseValue = (typeof Phase)[keyof typeof Phase];

export function phaseLabel(phase: number): string {
    switch (phase) {
        case Phase.Collect:
            return "Collect";
        case Phase.Accumulating:
            return "Accumulating";
        case Phase.Discovered:
            return "Discovered";
        case Phase.Settling:
            return "Settling";
        default:
            return `Unknown (${phase})`;
    }
}

// The program's zero-copy state stores integers as little-endian byte arrays
// (`le_field!`, alignment-1), so the generated decoders expose `*Le` byte
// fields. These helpers decode them back to numbers (mirrors bots/src/client.ts).
export function readU64le(bytes: ReadonlyArray<number> | Uint8Array): bigint {
    let v = 0n;
    for (let i = 7; i >= 0; i--) v = (v << 8n) | BigInt(bytes[i] ?? 0);
    return v;
}

export function readU32le(bytes: ReadonlyArray<number> | Uint8Array): number {
    let v = 0;
    for (let i = 3; i >= 0; i--) v = v * 256 + (bytes[i] ?? 0);
    return v;
}

export function readU16le(bytes: ReadonlyArray<number> | Uint8Array): number {
    return (bytes[0] ?? 0) + (bytes[1] ?? 0) * 256;
}

/** Signed 64-bit little-endian (e.g. a position's `size`). */
export function readI64le(bytes: ReadonlyArray<number> | Uint8Array): bigint {
    let v = 0n;
    for (let i = 7; i >= 0; i--) v = (v << 8n) | BigInt(bytes[i] ?? 0);
    // two's-complement sign extension for 64-bit
    if (v >= 1n << 63n) v -= 1n << 64n;
    return v;
}

/** Signed 128-bit little-endian (funding index is an i128). */
export function readI128le(bytes: ReadonlyArray<number> | Uint8Array): bigint {
    let v = 0n;
    for (let i = 15; i >= 0; i--) v = (v << 8n) | BigInt(bytes[i] ?? 0);
    // two's-complement sign extension for 128-bit
    if (v >= 1n << 127n) v -= 1n << 128n;
    return v;
}

/** Derive the order slab + event authority a submit_order needs. */
export async function deriveOrderPdas(
    market: Address,
): Promise<{ orderSlab: Address; eventAuthority: Address }> {
    const [orderSlab] = await findOrderSlabHeaderPda({ market });
    const [eventAuthority] = await findEventAuthorityPda();
    return { orderSlab, eventAuthority };
}

export async function deriveUserCollateralPda(owner: Address): Promise<Address> {
    const [pda] = await findUserCollateralPda({ owner });
    return pda;
}

export async function deriveVaultPda(collateralMint: Address): Promise<Address> {
    const [pda] = await findVaultPda({ collateralMint });
    return pda;
}

/** Vault authority PDA (`[b"vault_authority"]`) — signs withdrawals.
 *  Not exposed by the generated client; derived here to match the program. */
export async function deriveVaultAuthorityPda(): Promise<Address> {
    const [pda] = (await getProgramDerivedAddress({
        programAddress: TEMPO_PROGRAM,
        seeds: [getUtf8Encoder().encode("vault_authority")],
    })) as ProgramDerivedAddress;
    return pda;
}
